### ISSUE TITLE
How to generate "val_labels"?

### ISSUE THREAD

**Issue by Seraen** [tzt101/MichiGAN#17]
Hi, I would like to use my own data of pictures, and I am wondering how to get the "val_labels"? Thank you!

**Comment by Zlin0530** [comment]
Hi, did you solve the problem of how to get "val_labels", I also want to test it on my own dataset, but I don't know how to get "val_labels"

**Comment by Seraen** [comment]
> 

Hi, you can use semantic segmentation to get the mask of hair, and the images should be converted to binary images (0 for black, 1 for white).
