### ISSUE TITLE
How to generate hair mask images?

### ISSUE THREAD

**Issue by kimlia545** [tzt101/MichiGAN#18]
Hello. Thank you for your amazing work.
What model did you use to create label images(hair mask) in FFHQ?
I am trying to test "cal_orientation.py"

**Comment by kimlia545** [comment]
I haven't tested it, but this might help.
https://github.com/zllrunning/face-parsing.PyTorch

**Comment by Zlin0530** [comment]
你好，请问你知道怎么获得“label images”吗，我想在自己的数据集上进行测试

**Comment by Zlin0530** [comment]
Hi, do you know how to get "label images", I want to test it on my own dataset
