### ISSUE TITLE
how to generate orientation map

### ISSUE THREAD

**Issue by ValentiaSulli** [tzt101/MichiGAN#4]
Thanks for your works！ I want to train michigan on my own dataset, but I can not find the codes about extract orientation map. Could you please provide the relevant codes ?

**Comment by tzt101** [comment]
This part of the code belongs to Sanp Inc. I have applied for this code and will make it public as soon as I can get it.

**Comment by utc1205** [comment]
I see a class "orient" in cal_orient_stroke.py , so i want to ask if it's the correct way to generate orientation map?  thanks.

**Comment by tzt101** [comment]
This code is used to calculate the orientation map of generated image (see models/networks/loss.py) and is a little different from the code which is used to generate orientation ground truth (we do not smooth the orientation map when calculating orientation loss).

**Comment by wasupandceacar** [comment]
Could you elaborate what is applied to orientation ground truth when do smoothing?

**Comment by mirfan899** [comment]
any update on this?

**Comment by ValentiaSulli** [comment]
已收到您的邮件，谢谢

**Comment by JaksonYee** [comment]
Thanks for your works！ I want to train michigan on my own dataset, but I can not find the codes about extract orientation map. Could you please provide the relevant codes ?Thank you very much!

**Comment by tzt101** [comment]
You can use cal_orientation.py to generate new orientations on your own dataset.

**Comment by ValentiaSulli** [comment]
已收到您的邮件，谢谢
